name: continuous integration

on: 
  push:
    paths:
      - 'src/*.cpp'
      - '.clang-format'
      - 'Makefile'
      - '.github/**'
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/*.cpp'
      - 'include/*.hpp'

permissions:
    contents: write
    pull-requests: write

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies(clang-format & clang-tidy)
      run: sudo apt update && sudo apt install -y g++-14 && sudo apt install -y clang-format && sudo apt install -y clang-tidy && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 10

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        fetch-depth: 0

    - name: Run clang-format
      run: clang-format -i src/*.cpp src/*.hpp

    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: clang-format"
        commit_user_name: "github-actions[bot]"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
        commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        # commit_branch: ${{ github.head_ref }}

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies(g++)
      run: sudo apt update && sudo apt install -y g++-14 && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 10

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        fetch-depth: 0

    - name: Build project
      run: |
        make

    - name: Revert bad commit
      if: ${{ failure() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
      run: |
       git config --global user.email "github-actions[bot]@users.noreply.github.com"
       git config --global user.name "github-actions[bot]"
       git revert HEAD --no-edit
       git push --force

    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
          name: Artifact
          path: bin/
